"""add image_public_id to categories

Revision ID: 82654cf712f6
Revises: b9079d4bd723
Create Date: 2026-07-17 18:45:09.344159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82654cf712f6'
down_revision: Union[str, Sequence[str], None] = 'b9079d4bd723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_public_id', sa.String(length=255), nullable=True, comment='Cloudinary public ID'))
    op.alter_column('categories', 'image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               comment='Cloudinary image URL',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Cloudinary image URL',
               existing_nullable=True)
    op.drop_column('categories', 'image_public_id')
    # ### end Alembic commands ###
