"""add public_id to product_images

Revision ID: b9079d4bd723
Revises: 8a1f2c3d4e5f
Create Date: 2026-07-17 15:51:58.560501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9079d4bd723'
down_revision: Union[str, Sequence[str], None] = '8a1f2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_images",
        sa.Column(
            "public_id",
            sa.String(length=255),
            nullable=True,
            comment="Cloudinary public id",
        ),
    )
    op.alter_column('product_images', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Cloudinary image URL',
               existing_comment='Path or URL of the product image',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.alter_column('product_images', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Path or URL of the product image',
               existing_comment='Cloudinary image URL',
               existing_nullable=False)
    op.drop_column('product_images', 'public_id')
    # ### end Alembic commands ###
